<script lang="ts">
    import type { Snippet } from "svelte";
    let {
        class: className = "",
        label = undefined,
        children,
        ...restProps
    }: {
        label?: string;
        children: Snippet;
        [key: string]: unknown;
    } = $props();
</script>

<!-- SingaporeNationalRegistrationIdentityCardView.svelte -- generated by bin/new-component; replace <div> with the real semantic element -->
<div class={`singapore-national-registration-identity-card-view ${className}`} aria-label={label} {...restProps}>
    {@render children?.()}
</div>
